# Generated by Django 2.0.8 on 2019-07-01 13:08

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pricePerQuantity', models.IntegerField()),
                ('rating', django.contrib.postgres.fields.jsonb.JSONField()),
                ('orderCount', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
                ('imageUrl', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('dateOfCreation', models.DateTimeField()),
                ('costOfThisOrder', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resturant.Customer')),
                ('food', models.ManyToManyField(to='resturant.Food')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('choice_type', models.CharField(choices=[('1', 'booked'), ('2', 'reserved'), ('3', 'free')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('choice', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='orders',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resturant.Table'),
        ),
        migrations.AddField(
            model_name='food',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resturant.Type'),
        ),
    ]
