# Generated by Django 2.2.4 on 2019-08-03 14:10

import datetime
from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pricePerQuantity', models.IntegerField()),
                ('rating', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('orderCount', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=100)),
                ('imageUrl', models.URLField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='resturant.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('table_status', models.CharField(choices=[('1', 'booked'), ('2', 'reserved'), ('3', 'free')], max_length=1)),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='linked_user')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('dateOfCreation', models.DateTimeField()),
                ('costList', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None)),
                ('totalCost', models.IntegerField(default=0)),
                ('order_status', models.CharField(choices=[('1', 'pending'), ('2', 'confirmed')], max_length=1)),
                ('eta', models.DurationField(default=datetime.timedelta(0))),
                ('food', models.ManyToManyField(to='resturant.Food')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resturant.Table')),
            ],
        ),
        migrations.AddField(
            model_name='food',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='resturant.Type'),
        ),
    ]
