# Generated by Django 2.2.4 on 2019-08-03 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0003_auto_20190803_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_status',
            field=models.CharField(choices=[('1', 'pending'), ('2', 'confirmed')], default='1', max_length=1),
        ),
    ]
