# Generated by Django 2.2.4 on 2019-08-03 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0004_auto_20190803_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='User',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='current_table', to=settings.AUTH_USER_MODEL, verbose_name='linked_user'),
        ),
    ]
