# Generated by Django 2.2.4 on 2019-08-03 18:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0005_auto_20190803_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='food',
            field=models.ManyToManyField(null=True, to='resturant.Food'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='quantity',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None),
        ),
    ]
