# Generated by Django 2.2.4 on 2019-08-03 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0006_auto_20190803_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='food',
            field=models.ManyToManyField(default=[], to='resturant.Food'),
        ),
    ]
