# Generated by Django 2.2.4 on 2019-08-03 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0007_auto_20190803_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='food',
            field=models.ManyToManyField(to='resturant.Food'),
        ),
    ]
