# Generated by Django 2.2.4 on 2019-08-04 04:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0011_auto_20190803_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='costList',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, size=None),
        ),
        migrations.AlterField(
            model_name='orders',
            name='quantity',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None),
        ),
    ]
