# Generated by Django 2.2.4 on 2019-08-04 04:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0012_auto_20190804_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='costList',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='orders',
            name='quantity',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
    ]
