# Generated by Django 2.2.4 on 2019-08-05 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0014_restaurantinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantinfo',
            name='service_tax',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
        ),
    ]
